spring:
  redis:
    database: 5
    host: localhost
    port: 6379
#    password: hycxli#123
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://localhost:3306/smart-park-001?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: pass123
      # 从库数据源
      slave:
        #从数据源开关/默认关闭
        enabled: false
        url: jdbc:mysql://localhost:3306/smart-park-001?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: pass123
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /monitor/druid/*
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
# 本地文件上传路径
dfs:
  # 此处改成自己服务器存储位置
  path: /Users/XXXX/techworkspace/dpo-project/dpo-storage
#  domain: http://dpo.dtransfer.cn
#  path: /dpo/dpo-storage

## 公众号配置(必填)
# 小程序 appID secret
wx:
  miniapp:
    appid: xxxx
    secret: xxx
    token:
    aesKey:
    msgDataFormat: JSON              # 消息格式，XML或者JSON.
    # 存储配置redis(可选)
    # 注意: 指定redis.host值后不会使用容器注入的redis连接(JedisPool)
    config-storage:
      type: Jedis                     # 配置类型: Memory(默认), Jedis, RedisTemplate
      key-prefix: wa                  # 相关redis前缀配置: wa(默认)
      redis:
        host: localhost
        #        password: vdcity2111015
        port: 6379
      # http客户端配置
      http-client-type: HttpClient      # http客户端类型: HttpClient(默认), OkHttp, JoddHttp
      http-proxy-host:
      http-proxy-port:
      http-proxy-username:
      http-proxy-password:
# Sn
sn:
  product:
    prefix: 'yyyyMMdd'
    maxLo: 100
  order:
    prefix: 'yyyyMMdd'
    maxLo: 100
  orderPayment:
    prefix: 'yyyyMMdd'
    maxLo: 100
  orderRefunds:
    prefix: 'yyyyMMdd'
    maxLo: 100
  orderShipping:
    prefix: 'yyyyMMdd'
    maxLo: 100
  orderReturns:
    prefix: 'yyyyMMdd'
    maxLo: 100
  paymentTransaction:
    prefix: 'yyyyMMdd'
    maxLo: 100
  platformService:
    prefix: 'yyyyMMdd'
    maxLo: 100
mybatis-plus:
  configuration:
    default-enum-type-handler: cn.dtransfer.common.handlers.MybatisEnumTypeHandler

